###
POST https://localhost:5001/api/usuario/criar
Content-Type: application/json

{
    "Nickname" : "Bolacha",
    "Idade" : 20,
    "Pais" : "Brazil"
}

###
GET https://localhost:5001/api/usuario/listar

###
GET https://localhost:5001/api/usuario/listarId/1

###
DELETE https://localhost:5001/api/usuario/deletar/1

###
PUT https://localhost:5001/api/usuario/editar/1
Content-Type: application/json

{
    "Id"     : 2,
    "nickname" : "xXx-Bolacha-xXx",
    "idade" : 20,
    "pais" : "Portugal"
}